### PR TITLE
Rename `template` to `view_template`

### LINKED ISSUE #35: `def template` will be deprecated in Phlex 2.0
I just upgraded to Phlex 1.10 and my specs and features are spewing this deprecation message:

> ⚠️ [DEPRECATION] Defining the `template` method on a Phlex component will not be supported in Phlex 2.0. Please rename the method to `view_template` instead.

I will create a pull request that resolves this. (Please bear with me. It will be my first.)

### PR DESCRIPTION
**Pull request by joostvanrijn**
Phlex 2.0 will rename the template methods to view_template and `def template` will render a <template> tag.

Fixes #35

### CODE REVIEW

**Comment by bradgessler** [comment]
Thanks for the PR! Could you `alias :template :view_template` in `Superform::Field` for backwards compatibility with Phlex 1.x?

**Comment by joostvanrijn** [comment]
Sure can! Should I then also revert the change in the gemspec? So we'll depend op `~> 1.0` instead of `~> 1.2`?

**Comment by bradgessler** [comment]
Yeah, you can relax that gemspec too. I'm going to keep them compatible with each other as long as possible. Maybe in 1.x I'll make the breaking change that drops `template`.

**Comment by joostvanrijn** [comment]
Alright. This should do it then.

**Comment by joostvanrijn** [comment]
@bradgessler does this PR still require work on my side?

**Comment by bradgessler** [comment]
Nope! Just waiting as long as I can before merging this since Phlex 2.x isn't out and Phlex isn't pushing the change too hard (docs on the website still say `def template` at https://www.phlex.fun/ ... which maybe I could get changed?)

**Comment by joostvanrijn** [comment]
I see you've fixed this yourself? :) https://github.com/rubymonolith/superform/commit/7795d1c7d1d760445f291e7f4d2398bbda8e5500
Feel free to close this PR

**Comment by bradgessler** [comment]
Yep! haha, I got tired of seeing a bajillion of these deprecations messages when I fired up the production rails console.

**Pull request closed without merging**
